### ISSUE TITLE
Dependabot

### ISSUE THREAD

**Issue by JulienPalard** [Seluj78/poutils#4]
@Seluj78 Tu pourrais rajouter https://github.com/apps/dependabot-preview/installations/new? J'ai pas l'impression de pouvoir le faire.

**Comment by Seluj78** [comment]
Il est installé sur tous mes répos par defaut 👌

**Comment by JulienPalard** [comment]
Depuis 3h ou depuis toujours ? Car je ne le voit pas bumper powrap : https://pypi.org/project/powrap/

**Comment by Seluj78** [comment]
Depuis toujours mais je sais pas comment il marche

**Comment by Seluj78** [comment]
Désinstallé et réinstallé

**Comment by Seluj78** [comment]
En fait y'a un site en plus sur lequel faut gerer le truc, c'est en cours
